Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
    public int MachineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      var selectedEngineers = _db.EngineerMachine
        .Where(em => em.MachineId == id)
        .Select(engineer => engineer.EngineerId).ToList();
      ViewBag.EngineerId = new SelectList(_db.Engineers
        .Where(engineer => !selectedEngineers.Contains(engineer.EngineerId))
        .Select(engineer => engineer),
        "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId, int joinId)
    {
      if (EngineerId !=0)
      {
        var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
        _db.EngineerMachine.Remove(joinEntry);
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      var selectedEngineers = _db.EngineerMachine
        .Where(em => em.MachineId == id)
        .Select(engineer => engineer.EngineerId).ToList();
      ViewBag.EngineerId = new SelectList(_db.Engineers
        .Where(engineer => !selectedEngineers.Contains(engineer.EngineerId))
        .Select(engineer => engineer),
        "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
      public ActionResult AddEngineer(Machine machine, int EngineerId)
      {
        if (EngineerId != 0)
        {
          _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="header">Add an engineer</div>

<div class="subHeader">Add a licensed engineer for this machine: @Html.DisplayFor(model => model.Name)</div>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select engineer")
  @Html.DropDownList("EngineerId", "N/A")

  <input type="submit" value="Save" />
}

<p>Back to @Html.ActionLink("Machine List", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="subHeader">Add a new machine</div>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("select engineer")
  @Html.DropDownList("EngineerId")
  <input type="submit" value="add a new machine" />
}
<p>Show @Html.ActionLink("all machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="subHeader">Are you sure you want to remove this machine from the list?</div>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<p>Back to @Html.ActionLink("Machine List", "Index")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<div class="header">Machine Details</div>

<div class="subHeader">@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</div>

@if(Model.JoinEntities.Count == 0)
{
  <p>This machine has no licensed engineers</p>
}
else
{
  <div class="subHeader">Engineers that are licensed to run this machine: </div>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Engineer.Name</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>Back to @Html.ActionLink("Machines List", "Index")</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new {id = Model.MachineId })</p>
<p>Add a new @Html.ActionLink("licensed engineer", "AddEngineer", new { id = Model.MachineId }) for this machine</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Home Page", "Index", "Home")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="header">Edit</div>

<div class="subHeader">Edit this Machine: @Html.DisplayFor(model => model.Name)</div>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  @foreach (var join in Model.JoinEntities)
  {
      @Html.Hidden("joinId", @join.EngineerMachineId)
  }

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Select a licensed engineer")
  @Html.DropDownList("EngineerId", "N/A")
  <input type="submit" value="Save" />
}
<p>Back to @Html.ActionLink("Machine List", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<div class="header">Machines</div>

@if(@Model.Count == 0)
{
  <div class="subHeader">No machines have been added yet. sad face.</div>
}

<ul>
  @foreach(Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</li>
  }
</ul>
<p>Add a @Html.ActionLink("new machine", "Create")</p>
<p>Return to the @Html.ActionLink("Home Page", "Index", "Home")</p>